/**
 * @fileoverview Utility functions for the Whisper Music OS.
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { MusicalData, NoteEvent } from '@/schema.ts';

/**
 * Triggers haptic feedback on supported devices.
 * @param pattern A number for milliseconds or an array for a vibration pattern.
 */
export function hapticFeedback(pattern: number | number[] = 5): void {
    if ('vibrate' in navigator && navigator.vibrate) {
        try {
            navigator.vibrate(pattern);
        } catch (e) {
            // Vibration can fail for various reasons (e.g., user settings, not in focus).
            // It's not critical, so we can ignore the error.
        }
    }
}

// Helper to format seconds into mm:ss format
export function formatDuration(seconds: number): string {
    if (!isFinite(seconds) || seconds < 0) {
        return '0:00';
    }
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.floor(seconds % 60);
    const paddedSeconds = remainingSeconds < 10 ? `0${remainingSeconds}` : remainingSeconds;
    return `${minutes}:${paddedSeconds}`;
}

// Helper to convert an AudioBuffer to a WAV file blob
export function audioBufferToWav(buffer: AudioBuffer): Blob {
    const numOfChan = buffer.numberOfChannels;
    const length = buffer.length * numOfChan * 2 + 44;
    const bufferOut = new ArrayBuffer(length);
    const view = new DataView(bufferOut);
    const channels = [];
    let i, sample;
    let offset = 0;
    let pos = 0;

    // write WAVE header
    setUint32(0x46464952); // "RIFF"
    setUint32(length - 8); // file length - 8
    setUint32(0x4556157); // "WAVE"

    setUint32(0x20746d66); // "fmt " chunk
    setUint32(16); // length = 16
    setUint16(1); // PCM (uncompressed)
    setUint16(numOfChan);
    setUint32(buffer.sampleRate);
    setUint32(buffer.sampleRate * 2 * numOfChan); // avg. bytes/sec
    setUint16(numOfChan * 2); // block-align
    setUint16(16); // 16-bit
    setUint32(0x61746164); // "data" - chunk
    setUint32(length - pos - 4); // chunk length

    function setUint16(data: number) {
        view.setUint16(pos, data, true);
        pos += 2;
    }

    function setUint32(data: number) {
        view.setUint32(pos, data, true);
        pos += 4;
    }

    // write interleaved data
    for (i = 0; i < numOfChan; i++) {
        channels.push(buffer.getChannelData(i));
    }

    while (pos < length) {
        for (i = 0; i < numOfChan; i++) {
            sample = Math.max(-1, Math.min(1, channels[i][offset])); // clamp
            sample = (0.5 + sample < 0 ? sample * 32768 : sample * 32767) | 0; // scale to 16-bit signed int
            view.setInt16(pos, sample, true); // write 16-bit sample
            pos += 2;
        }
        offset++;
    }

    return new Blob([view], { type: 'audio/wav' });
}

// --- Music Theory Utilities ---
const NOTES: { [key: string]: number } = {
    'C': 0, 'C#': 1, 'Db': 1, 'D': 2, 'D#': 3, 'Eb': 3, 'E': 4, 'F': 5,
    'F#': 6, 'Gb': 6, 'G': 7, 'G#': 8, 'Ab': 8, 'A': 9, 'A#': 10, 'Bb': 10, 'B': 11
};

/**
 * Converts a musical note in scientific pitch notation (e.g., "C#4") to its corresponding frequency in Hz.
 * @param note The note string to convert.
 * @returns The frequency in Hz, or 0 if the note format is invalid.
 */
export function noteToFreq(note: string): number {
    const a4 = 440;
    const noteNameRegex = /^([A-G])([#b]?)(-?\d+)$/;
    const match = note.match(noteNameRegex);

    if (!match) {
        console.warn(`Invalid note format: ${note}`);
        return 0;
    }

    const [, key, accidental, octaveStr] = match;
    const octave = parseInt(octaveStr, 10);
    
    let semitone = NOTES[key];
    if (accidental === '#') semitone++;
    else if (accidental === 'b') semitone--;
    
    // MIDI note number calculation where C4=60, A4=69.
    const noteNumber = semitone + (octave + 1) * 12;
    
    return a4 * Math.pow(2, (noteNumber - 69) / 12);
}


/**
 * Renders an audio track from structured musical data using a professional multi-bus architecture.
 * This function acts as a high-fidelity renderer for compositions generated by an AI agent.
 */
export async function generateProceduralAudio(options: {
    audioContext: AudioContext;
    duration: number;
    musicalData: MusicalData;
    instrumentDescriptions?: {
        drums: string,
        bassline: string,
        melody: string,
        pads: string
    };
    saturation?: number;
    stereoWidth?: number;
    vocalParams?: { // Kept for vocal generation
        emotion: string;
        articulation: number;
        breathControl: number;
        vibrato: number;
        pitchVariation: number;
        deliveryTiming: number;
    };
    genre?: string; // Kept for vocal generation logic
}): Promise<AudioBuffer> {
    const { audioContext, duration, musicalData, instrumentDescriptions, stereoWidth = 1, vocalParams, genre } = options;
    const desc = instrumentDescriptions || { drums: '', bassline: '', melody: '', pads: '' };
    
    const totalDuration = duration;
    const offlineCtx = new OfflineAudioContext(2, Math.ceil(audioContext.sampleRate * totalDuration), audioContext.sampleRate);

    // --- Create Master Bus ---
    const masterBus = offlineCtx.createGain();

    // "Glue" compressor for the master bus
    const masterCompressor = offlineCtx.createDynamicsCompressor();
    masterCompressor.threshold.setValueAtTime(-18, 0);
    masterCompressor.knee.setValueAtTime(25, 0);
    masterCompressor.ratio.setValueAtTime(4, 0);
    masterCompressor.attack.setValueAtTime(0.01, 0);
    masterCompressor.release.setValueAtTime(0.3, 0);

    // Final output gain/limiter
    const masterGain = offlineCtx.createGain();
    masterGain.gain.value = 0.95; // Leave a little headroom

    // Master Chain: masterBus -> compressor -> gain -> destination
    masterBus.connect(masterCompressor).connect(masterGain).connect(offlineCtx.destination);
    
    // --- Create Adaptive Mix Buses ---
    const drumBus = offlineCtx.createGain();
    const bassBus = offlineCtx.createGain();
    const harmonyBus = offlineCtx.createGain();

    // --- Apply Bus Processing ---

    // Drum Bus: Punchy Compressor for cohesion and impact
    const drumCompressor = offlineCtx.createDynamicsCompressor();
    drumCompressor.threshold.setValueAtTime(-15, 0);
    drumCompressor.ratio.setValueAtTime(5, 0);
    drumCompressor.attack.setValueAtTime(0.003, 0);
    drumBus.connect(drumCompressor).connect(masterBus);

    // Bass Bus: Dynamic Control Compressor for a solid low-end
    const bassCompressor = offlineCtx.createDynamicsCompressor();
    bassCompressor.threshold.setValueAtTime(-20, 0);
    bassCompressor.ratio.setValueAtTime(6, 0);
    bassCompressor.attack.setValueAtTime(0.005, 0);
    bassCompressor.release.setValueAtTime(0.2, 0);
    bassBus.connect(bassCompressor).connect(masterBus);

    // Harmony Bus: Clarity (High-pass) & Space (Reverb Send)
    const harmonyHighpass = offlineCtx.createBiquadFilter();
    harmonyHighpass.type = 'highpass';
    harmonyHighpass.frequency.value = 150; // Cut out potential mud

    // Reverb effect for harmony bus (send/return architecture)
    const harmonyReverb = offlineCtx.createConvolver();
    const harmonyReverbMix = offlineCtx.createGain();
    harmonyReverbMix.gain.value = 0.25; // How much reverb to mix in

    // Create a simple procedural impulse response for the reverb
    const impulseLength = offlineCtx.sampleRate * 1.5; // 1.5s reverb tail
    const impulse = offlineCtx.createBuffer(2, impulseLength, offlineCtx.sampleRate);
    const impulseL = impulse.getChannelData(0);
    const impulseR = impulse.getChannelData(1);
    for (let i = 0; i < impulseLength; i++) {
        const decay = Math.pow(1 - i / impulseLength, 2.5);
        impulseL[i] = (Math.random() * 2 - 1) * decay;
        impulseR[i] = (Math.random() * 2 - 1) * decay;
    }
    harmonyReverb.buffer = impulse;

    // Connect Harmony Bus Chain:
    // 1. Main signal path (dry)
    harmonyBus.connect(harmonyHighpass).connect(masterBus);
    // 2. Send to reverb (wet)
    harmonyHighpass.connect(harmonyReverb).connect(harmonyReverbMix).connect(masterBus);

    // --- Synthesis Utilities (Inner Functions) ---
    function createSynthVoice(startTime: number, noteDuration: number, freq: number, targetBus: AudioNode, waveform: OscillatorType = 'triangle', pan = 0, filterFreq = 20000, volume = 0.5, velocity = 1.0, description: string = '', vocalParams?: { emotion: string; articulation: number; breathControl: number; vibrato: number; pitchVariation: number; deliveryTiming: number; }) {
        const osc1 = offlineCtx.createOscillator();
        const osc2 = offlineCtx.createOscillator();
        const gainNode = offlineCtx.createGain();
        const panner = offlineCtx.createStereoPanner();
        const filter = offlineCtx.createBiquadFilter();

        let finalWaveform = waveform;
        let vibratoAmount = 0;
        let vibratoSpeed = 5;
        let finalVolume = volume;
        let finalFilterFreq = filterFreq;
        let filterRampTo = finalFilterFreq * 0.4;
        let attackTime = 0.005;
        let releaseTime = 0.1;

        const lowerDesc = description.toLowerCase();
        // Waveform selection based on description
        if (lowerDesc.includes('aggressive') || lowerDesc.includes('bright') || lowerDesc.includes('saw')) {
            finalWaveform = 'sawtooth';
        } else if (lowerDesc.includes('square') || lowerDesc.includes('hollow')) {
            finalWaveform = 'square';
        } else if (lowerDesc.includes('warm') || lowerDesc.includes('soft') || lowerDesc.includes('pad')) {
            finalWaveform = 'triangle';
        }

        // Envelope adjustments based on description
        if (lowerDesc.includes('pluck') || lowerDesc.includes('short') || lowerDesc.includes('staccato')) {
            attackTime = 0.001;
            releaseTime = 0.05;
        } else if (lowerDesc.includes('long') || lowerDesc.includes('sustain') || lowerDesc.includes('pad')) {
            attackTime = 0.1;
            releaseTime = 0.5;
        }

        // Filter adjustments based on description
        if (lowerDesc.includes('dark') || lowerDesc.includes('muffled')) {
            finalFilterFreq = 800;
            filterRampTo = 400;
        } else if (lowerDesc.includes('bright') || lowerDesc.includes('crisp')) {
            finalFilterFreq = 8000;
            filterRampTo = 3000;
        }
        
        if (vocalParams) {
            switch (vocalParams.emotion) {
                case 'Sad':
                    vibratoAmount += 1.5;
                    vibratoSpeed = 4.5;
                    filterRampTo = finalFilterFreq * 0.2;
                    break;
                case 'Happy':
                    finalFilterFreq *= 1.2;
                    filterRampTo = finalFilterFreq * 0.5;
                    break;
                case 'Energetic':
                    finalVolume *= 1.2;
                    break;
                case 'Aggressive':
                    finalWaveform = 'sawtooth';
                    break;
            }
            const vibratoValue = vocalParams.vibrato ?? 0.4;
            vibratoAmount += vibratoValue * 7;
            vibratoSpeed += (vibratoValue - 0.5) * 3;
            attackTime = 0.005 + (1 - (vocalParams.articulation ?? 0.5)) * 0.1;
            releaseTime = 0.1 + (1 - (vocalParams.breathControl ?? 0.5)) * 0.4;
        }

        const pitchVarAmount = (vocalParams?.pitchVariation ?? 0.3) * 1.0;
        const pitchOffset = (Math.random() - 0.5) * pitchVarAmount;
        const finalFreq = freq * Math.pow(2, pitchOffset / 12);

        osc1.type = finalWaveform;
        osc2.type = finalWaveform;
        osc1.frequency.setValueAtTime(finalFreq, startTime);
        osc2.frequency.setValueAtTime(finalFreq * 1.005, startTime);

        if (vibratoAmount > 0) {
            const lfo = offlineCtx.createOscillator();
            lfo.type = 'sine';
            lfo.frequency.value = vibratoSpeed;
            const lfoGain = offlineCtx.createGain();
            lfoGain.gain.value = vibratoAmount;
            lfo.connect(lfoGain);
            lfoGain.connect(osc1.frequency);
            lfoGain.connect(osc2.frequency);
            lfo.start(startTime);
            lfo.stop(startTime + noteDuration);
        }

        // --- Dynamic Panning Logic ---
        let finalPan = pan;

        if (lowerDesc.includes('centered') || lowerDesc.includes('mono')) {
            finalPan = 0;
        } else if (lowerDesc.includes('left')) {
            finalPan = -0.75;
        } else if (lowerDesc.includes('right')) {
            finalPan = 0.75;
        } else if (lowerDesc.includes('wide')) {
            finalPan = (Math.random() - 0.5) * 1.6; // -0.8 to 0.8
        }

        const isSweeping = lowerDesc.includes('sweep') || lowerDesc.includes('pan') || lowerDesc.includes('move') || lowerDesc.includes('drift');

        if (isSweeping) {
            const startPan = (Math.random() - 0.5) * 1.8;
            const endPan = -startPan * (0.5 + Math.random() * 0.5);
            panner.pan.setValueAtTime(startPan, startTime);
            panner.pan.linearRampToValueAtTime(endPan, startTime + noteDuration);
        } else {
            panner.pan.setValueAtTime(finalPan * stereoWidth, startTime);
        }

        filter.type = 'lowpass';
        filter.Q.value = 1;
        filter.frequency.setValueAtTime(finalFilterFreq, startTime);
        filter.frequency.linearRampToValueAtTime(filterRampTo, startTime + noteDuration);

        gainNode.gain.setValueAtTime(0, startTime);
        gainNode.gain.linearRampToValueAtTime(finalVolume * velocity, startTime + attackTime);
        const effectiveReleaseTime = Math.max(0.01, Math.min(releaseTime, noteDuration - attackTime));
        gainNode.gain.setValueAtTime(finalVolume * velocity, startTime + noteDuration - effectiveReleaseTime);
        gainNode.gain.linearRampToValueAtTime(0, startTime + noteDuration);
        
        osc1.connect(filter);
        osc2.connect(filter);
        filter.connect(panner);
        panner.connect(gainNode);
        gainNode.connect(targetBus);
        
        osc1.start(startTime);
        osc1.stop(startTime + noteDuration);
        osc2.start(startTime);
        osc2.stop(startTime + noteDuration);
    }
    
    function createDrumHit(startTime: number, type: 'kick' | 'snare' | 'closed' | 'open', targetBus: AudioNode, volume = 1.0, velocity = 1.0, description: string = '') {
        let pan = 0;
        const lowerDesc = description.toLowerCase();

        if (type === 'closed' || type === 'open') {
            pan = (Math.random() > 0.5 ? 1 : -1) * 0.2; // Default slight pan for hats
        }

        if (lowerDesc.includes('centered') || lowerDesc.includes('mono')) {
            pan = 0;
        } else if (lowerDesc.includes('wide')) {
            if (type === 'closed' || type === 'open') {
                pan = (Math.random() > 0.5 ? 1 : -1) * (0.4 + Math.random() * 0.4); // Wider pan for hats
            }
        }
        
        const panner = offlineCtx.createStereoPanner();
        panner.pan.setValueAtTime(pan * stereoWidth, startTime);
        panner.connect(targetBus);
        let finalNode: AudioNode | undefined;

        if (type === 'kick') {
            const osc = offlineCtx.createOscillator();
            const gain = offlineCtx.createGain();
            osc.type = 'sine';
            osc.frequency.setValueAtTime(120, startTime);
            osc.frequency.exponentialRampToValueAtTime(0.001, startTime + 0.5);
            gain.gain.setValueAtTime(volume * velocity, startTime);
            gain.gain.exponentialRampToValueAtTime(0.001, startTime + 0.5);
            osc.connect(gain);
            finalNode = gain;
            osc.start(startTime);
            osc.stop(startTime + 0.5);
        } else if (type === 'snare') {
            const noise = offlineCtx.createBufferSource();
            const bufferSize = offlineCtx.sampleRate * 0.5;
            const buffer = offlineCtx.createBuffer(1, bufferSize, offlineCtx.sampleRate);
            const data = buffer.getChannelData(0);
            for (let i = 0; i < bufferSize; i++) {
                data[i] = Math.random() * 2 - 1;
            }
            noise.buffer = buffer;

            const filter = offlineCtx.createBiquadFilter();
            filter.type = 'bandpass';
            filter.frequency.value = 1500;
            filter.Q.value = 1.5;

            const gain = offlineCtx.createGain();
            gain.gain.setValueAtTime(volume * velocity * 0.8, startTime);
            gain.gain.exponentialRampToValueAtTime(0.01, startTime + 0.2);
            noise.connect(filter).connect(gain);
            finalNode = gain;
            noise.start(startTime);
            noise.stop(startTime + 0.5);
        } else if (type === 'closed' || type === 'open') {
             const noise = offlineCtx.createBufferSource();
            const bufferSize = offlineCtx.sampleRate * 0.5;
            const buffer = offlineCtx.createBuffer(1, bufferSize, offlineCtx.sampleRate);
            const data = buffer.getChannelData(0);
            for (let i = 0; i < bufferSize; i++) {
                data[i] = Math.random() * 2 - 1;
            }
            noise.buffer = buffer;
            const filter = offlineCtx.createBiquadFilter();
            filter.type = 'highpass';
            filter.frequency.value = 5000;
            const gain = offlineCtx.createGain();
            const decay = type === 'closed' ? 0.05 : 0.4;
            gain.gain.setValueAtTime(volume * velocity * 0.4, startTime);
            gain.gain.exponentialRampToValueAtTime(0.01, startTime + decay);
            noise.connect(filter).connect(gain);
            finalNode = gain;
            noise.start(startTime);
            noise.stop(startTime + 0.5);
        }
        
        if (finalNode) {
            finalNode.connect(panner);
        }
    }
    
    // --- Scheduling Loop (Renderer) ---
    // Special case for vocal generation, which still uses procedural logic for now
    if (genre === 'vocal_melody' && vocalParams) {
        // This is a simplified procedural melody to represent a vocal line.
        // It uses the passed vocalParams for an expressive performance.
        const notesInScale = 7;
        let noteIndex = 3;
        const quarterNoteTime = 60 / 120; // Assume 120bpm for vocals
        for (let time = 0; time < totalDuration - quarterNoteTime; time += quarterNoteTime * (0.5 + Math.random())) {
            const freq = noteToFreq(`C${4 + Math.floor(noteIndex / notesInScale)}`); // Simplified key
            const noteDuration = quarterNoteTime * (0.5 + Math.random() * 1.5);
            createSynthVoice(time, noteDuration, freq, harmonyBus, 'sine', 0, 5000, 0.6, 1.0, '', vocalParams);
            noteIndex += (Math.random() > 0.5 ? 1 : -1);
        }
    } else {
        // Render from structured musical data
        musicalData.drums?.forEach(noteEvent => {
            const drumType = noteEvent.note as 'kick' | 'snare' | 'closed' | 'open';
            createDrumHit(noteEvent.time, drumType, drumBus, 1.0, noteEvent.velocity, desc.drums);
        });

        musicalData.bassline?.forEach(noteEvent => {
            const freq = noteToFreq(noteEvent.note);
            if (freq > 0) createSynthVoice(noteEvent.time, noteEvent.duration, freq, bassBus, 'sine', 0, 800, 0.8, noteEvent.velocity, desc.bassline);
        });

        musicalData.melody?.forEach(noteEvent => {
            const freq = noteToFreq(noteEvent.note);
            if (freq > 0) createSynthVoice(noteEvent.time, noteEvent.duration, freq, harmonyBus, 'triangle', Math.random() - 0.5, 3000, 0.4, noteEvent.velocity, desc.melody);
        });

        musicalData.pads?.forEach(noteEvent => {
            const freq = noteToFreq(noteEvent.note);
            if (freq > 0) createSynthVoice(noteEvent.time, noteEvent.duration, freq, harmonyBus, 'sawtooth', (Math.random() - 0.5) * 0.8, 1200, 0.2, noteEvent.velocity, desc.pads);
        });
    }
    
    return offlineCtx.startRendering();
}